main: de.theunrealflo.speedrunaddon.SpeedrunMain
name: SpeedrunAddon
version: 1.0
depend: [ Stopwatch ]
author: TheUnreal_Flo_
description: An addon for Stopwatch Plugin to make an automation for speedruns.
